# Generated by Django 6.1 on 2026-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waiting_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surge_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toll_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parking_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waiting_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurgePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
