# Generated by Django 6.1 on 2026-09-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('pricing', '0001_initial'),
        ('rides', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farebreakdown',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fare', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='farerule',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_rules', to='locations.city'),
        ),
        migrations.AddField(
            model_name='farerule',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_rules', to='vehicles.vehicletype'),
        ),
        migrations.AddField(
            model_name='surgepricing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city'),
        ),
        migrations.AddField(
            model_name='surgepricing',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletype'),
        ),
    ]
