# Generated by Django 6.1 on 2026-09-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverearning',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver_earning', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='drivers.driver'),
        ),
    ]
