# Generated by Django 6.1 on 2026-09-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_gallery_my_file_gallery_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='profile_image',
            field=models.ImageField(help_text='Required: Upload a gallery image', upload_to='profileimg/'),
        ),
    ]
