# Generated by Django 6.1 on 2026-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_groupstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=30)),
                ('location', models.CharField(default='Haridwar, Uttarakhand', max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=150)),
                ('skills', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('application_email', models.EmailField(default='nandirides@gmail.com', max_length=254)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('coming_soon', 'Coming Soon'), ('closed', 'Closed')], default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
