# Generated by Django 6.1 on 2026-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Enquiry'), ('ride', 'Ride Support'), ('booking', 'Booking Issue'), ('payment', 'Payment Issue'), ('account', 'Account Support'), ('driver', 'Driver Support'), ('feedback', 'Feedback'), ('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('other', 'Other')], default='feedback', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
