# Generated by Django 6.1 on 2026-09-10 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('locations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('system', 'System'), ('admin', 'Admin')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('charge_applicable', models.BooleanField(default=False)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_number', models.CharField(max_length=50, unique=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('driver_arrived', 'Driver Arrived'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='driver_assigned', max_length=30)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='drivers.driver')),
                ('drop_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_drops', to='locations.location')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_pickups', to='locations.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_text', models.TextField(blank=True)),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rides.cancellationreason')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='rides.ride')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideDriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_assignments', to='drivers.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='rides.ride')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching_driver', 'Searching Driver'), ('driver_assigned', 'Driver Assigned'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed')], db_index=True, default='requested', max_length=30)),
                ('drop_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_requests', to='locations.location')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to='locations.location')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ride', to='rides.riderequest'),
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rides.ride')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ride', 'from_user', 'to_user'), name='unique_ride_rating')],
            },
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_order', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.ride')),
            ],
            options={
                'ordering': ['stop_order'],
                'constraints': [models.UniqueConstraint(fields=('ride', 'stop_order'), name='unique_ride_stop_order')],
            },
        ),
        migrations.CreateModel(
            name='RideTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='rides.ride')),
            ],
            options={
                'indexes': [models.Index(fields=['ride', '-recorded_at'], name='rides_ridet_ride_id_8dfbe2_idx')],
            },
        ),
    ]
