# Generated by Django 6.1 on 2026-09-15 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=200, unique=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('ride_type', models.CharField(max_length=200)),
                ('ride_date', models.CharField(max_length=200)),
                ('ride_time', models.CharField(max_length=200)),
                ('ride_status', models.CharField(max_length=200)),
                ('passengers', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('base_fare', models.CharField(max_length=200)),
                ('ride_charge', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
                ('platform_fee', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=200)),
                ('completed_ride', models.CharField(max_length=200)),
                ('total_ride', models.CharField(max_length=200)),
                ('total_spent', models.CharField(max_length=200)),
                ('fare', models.CharField(max_length=200)),
                ('estimate_fare', models.CharField(max_length=200)),
                ('your_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_phone', models.CharField(max_length=200)),
                ('driver_email', models.CharField(max_length=200)),
                ('driver_registration', models.CharField(max_length=200)),
                ('driver_status', models.CharField(max_length=200)),
                ('driver_arrival', models.CharField(max_length=200)),
                ('dl_number', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_insurance', models.CharField(max_length=200)),
                ('vehicle_pollution', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('documnet_upload', models.FileField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirmpassword', models.CharField(max_length=200)),
                ('oldpassword', models.CharField(max_length=200)),
                ('newpassword', models.CharField(max_length=200)),
                ('newconfirmpassword', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('village_colony', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('USA', 'USA'), ('CHINA', 'CHINA')], max_length=20)),
                ('state', models.CharField(choices=[('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('CDG', 'Chandigarh')], max_length=20)),
                ('district', models.CharField(choices=[('AGC', 'AGRA'), ('VNR', 'VARANASI'), ('MTJ', 'MATHURA')], max_length=20)),
                ('mobilenumber', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
                ('regdate', models.CharField(max_length=200)),
                ('dlnumber', models.CharField(max_length=200)),
                ('vehiclenumber', models.CharField(max_length=200)),
                ('vehicleinsurance', models.CharField(max_length=200)),
                ('vehiclepollution', models.CharField(max_length=200)),
                ('vehicletype', models.CharField(max_length=200)),
                ('documnetupload', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=200)),
                ('ride_date', models.CharField(max_length=200)),
                ('ride_time', models.CharField(max_length=200)),
                ('ride_type', models.CharField(max_length=200)),
                ('ride_track', models.CharField(max_length=200)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_ride', to='user.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=200)),
                ('payment_date', models.CharField(max_length=200)),
                ('payment_time', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('payment_receipt', models.CharField(max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.booking')),
            ],
        ),
    ]
