# Generated by Django 6.1 on 2026-09-08 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirmpassword', models.CharField(max_length=200)),
                ('oldpassword', models.CharField(max_length=200)),
                ('newpassword', models.CharField(max_length=200)),
                ('newconfirmpassword', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('village_colony', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('USA', 'USA'), ('CHINA', 'CHINA')], max_length=20)),
                ('state', models.CharField(choices=[('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('CDG', 'Chandigarh')], max_length=20)),
                ('district', models.CharField(choices=[('AGC', 'AGRA'), ('VNR', 'VARANASI'), ('MTJ', 'MATHURA')], max_length=20)),
                ('mobilenumber', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
                ('regdate', models.CharField(max_length=200)),
                ('dlnumber', models.CharField(max_length=200)),
                ('vehiclenumber', models.CharField(max_length=200)),
                ('vehicleinsurance', models.CharField(max_length=200)),
                ('vehiclepollution', models.CharField(max_length=200)),
                ('vehicletype', models.CharField(max_length=200)),
                ('documnetupload', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
