# Generated by Django 6.1 on 2026-09-10 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=200, unique=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('ride_type', models.CharField(max_length=200)),
                ('ride_date', models.CharField(max_length=200)),
                ('ride_time', models.CharField(max_length=200)),
                ('ride_status', models.CharField(max_length=200)),
                ('passengers', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('base_fare', models.CharField(max_length=200)),
                ('ride_charge', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
                ('platform_fee', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=200)),
                ('completed_ride', models.CharField(max_length=200)),
                ('total_ride', models.CharField(max_length=200)),
                ('total_spent', models.CharField(max_length=200)),
                ('fare', models.CharField(max_length=200)),
                ('estimate_fare', models.CharField(max_length=200)),
                ('your_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_phone', models.CharField(max_length=200)),
                ('driver_email', models.CharField(max_length=200)),
                ('driver_registration', models.CharField(max_length=200)),
                ('driver_status', models.CharField(max_length=200)),
                ('driver_arrival', models.CharField(max_length=200)),
                ('dl_number', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_insurance', models.CharField(max_length=200)),
                ('vehicle_pollution', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('documnet_upload', models.FileField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='MyRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=200)),
                ('ride_date', models.CharField(max_length=200)),
                ('ride_time', models.CharField(max_length=200)),
                ('ride_type', models.CharField(max_length=200)),
                ('ride_track', models.CharField(max_length=200)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_ride', to='user.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=200)),
                ('payment_date', models.CharField(max_length=200)),
                ('payment_time', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=200)),
                ('payment_receipt', models.CharField(max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.booking')),
            ],
        ),
    ]
