# Generated by Django 6.1 on 2026-09-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_booking_driver_myride_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
